server:
  port: 9090

keycloak:
  realm: YOUR_KEYCLOAK_REALM_NAME
  auth-server-url: YOUR_KEYCLOAK_URL
  ssl-required: none
  resource: YOUR_KEYCLOAK_CLIENT_NAME
  credentials:
    secret: YOUR_KEYCLOAK_CLIENT_SECRET
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: YOUR_KEYCLOAK_MASTER_USER_USERNAME
    password: YOUR_KEYCLOAK_MASTER_USER_PASSWORD
  realm: master
  client: YOUR_KEYCLOAK_MASTER_CLIENT_NAME
